<?php $f = new NumberFormatter('ru', NumberFormatter::SPELLOUT); ?>
<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Приложение №1</title>
    <meta name="author" content="b7" />
    <meta name="title" content="Приложение №1" />
    <meta name="company" content="b7" />
    <style>
        body {
            font-family: DejaVu Sans, serif;}
        * {font-family: DejaVu Sans, serif; font-size: 10pt;}
        a.NoteRef {text-decoration: none;}
        hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 0 solid #CCC;}
        table {border: 0 solid transparent; border-spacing: 0; width : 100%; border-collapse: collapse;}
        td {border: 0 solid transparent; border-collapse: collapse;}
        .Normal {margin-top: 0; margin-bottom: 0;}
        h1 {font-size: 12pt; text-align: center; font-weight: bold; margin-top: 0; }
        h2 {font-size: 10pt; text-align: center; font-weight: bold; margin-top: 0; margin-bottom: 0;}
        h3 {color: #000000; font-weight: bold; text-decoration: underline ;}
        h4 {font-weight: bold; text-decoration: underline ;}
        h5 {font-size: 13pt; font-weight: bold; font-style: italic;}
        .Основной текст Знак {font-family: DejaVu Sans, serif;; font-size: 16pt; color: #000000; font-weight: bold;}
        .Интернет-ссылка {color: #0000FF; text-decoration: underline ;}
        .Strong {font-weight: bold;}
        .Верхний колонтитул Знак {font-family: DejaVu Sans, serif; font-size: 12pt;}
        .Нижний колонтитул Знак {font-family: DejaVu Sans, serif; font-size: 12pt;}
        .Заголовок 1 Знак {font-family: DejaVu Sans, serif; font-size: 14pt;}
        .fill {color: #FF0000; font-weight: bold; font-style: italic;}
        .Заголовок {font-family: DejaVu Sans, serif; font-size: 14pt;}
        .Body Text {font-size: 16pt; color: #000000; font-weight: bold;}
        .List {font-family: DejaVu Sans, serif;}
        .Caption {font-family: DejaVu Sans, serif; font-size: 12pt; font-style: italic;}
        .Указатель {font-family: DejaVu Sans, serif;}
        .Текст блока {font-family: DejaVu Sans, serif;}
        .Document Map {font-family: DejaVu Sans, serif;}
        .Верхний и нижний колонтитулы {margin-top: 0; margin-bottom: 0;}
        .Header {margin-top: 0; margin-bottom: 0;}
        .Footer {margin-top: 0; margin-bottom: 0;}
        .Body Text 2 {color: #000000;}
        .Body Text 3 {font-size: 8pt;}
        .Основной текст 21 {font-family: DejaVu Sans, serif; font-size: 12pt;}
        .Body Text 21 {font-family: DejaVu Sans, serif; font-size: 12pt;}
        .Normal (Web) {font-family: DejaVu Sans, serif; font-size: 11pt;}
        .page-break {
            page-break-after: always;
        }
        body { font-family: DejaVu Sans, serif; }
        p {margin-top: 0; margin-bottom: 0; text-align: justify;}
    </style>
</head>
<body>
<h1><span>Договор оказания услуг </span></h1>
<table style="table-layout: auto; border: transparent;">
    <tr>
        <td>
            <p><span>Улан-Удэ</span></p>
        </td>
        <td>
            <p style="text-align: right; margin-top: 0; margin-bottom: 0;"><span>21.12.2002 г.</span></p>
        </td>
    </tr>
</table>

<p>
    <span >
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aut et eum fuga harum porro, possimus suscipit veritatis? Aliquam animi architecto at beatae consequatur et eum eveniet ex facere, facilis fuga fugit id illum incidunt ipsa ipsum iste laboriosam laborum magnam minus modi mollitia perferendis quaerat qui quia, saepe voluptatibus?
    </span>
</p>

<h2><span >1. Предмет Договора</span></h2>

<p><span >1.1. В соответствии с настоящим Договором Исполнитель обязуется по заданию Заказчика выполнить работу по
        -23840923094820384. Исполнитель оказывает следующие виды услуг:</span></p>

<p><span>1.2. Стоимость выполнения Работы утверждается сторонами в пункте 3.1 настоящего договора.</span></p>

<p><span>1.3. Срок выполнения Работы Исполнителем утверждается сторонами и составляет 10 дней с момента заключения договора.</span></p>

<p><span>1.4. Работа считается выполненной Исполнителем после подписания «Акта выполненных работ» Заказчиком.</span></p>

<h2><span>2. Права и обязанности сторон</span></h2>
<p><span>2.1. В соответствии с настоящим Договором Заказчик вправе:</span></p>

<p><span>2.1.1. В любое время запросить отчет о ходе исполнения работ.</span></p>

<p style="margin-top: 7px;"><span>2.2. В соответствии с настоящим Договором Заказчик обязан:</span></p>

<p><span>2.2.1. Назначить ответственное лицо,  с которым будет контактировать Исполнитель, и только с этим лицом вести все переговоры. Назначенное ответственное лицо должно иметь доверенность со стороны Заказчика на внесение изменений в процессы работы и подписание закрывающих документов.</span></p>

<p><span>2.2.2. Предоставить необходимые материалы и данные. </span></p>

<p><span>2.2.3. Принять результат выполненной Работы с участием Исполнителя.</span></p>

<p><span>2.2.4. Оплатить Работу Исполнителя в размере, порядке и сроки, предусмотренные настоящим Договором.</span></p>

<p><span>2.2.5. Своевременно предоставлять Исполнителю информацию о событиях, способных негативно отразиться на ходе выполнения работ.  </span></p>

<p style="margin-top: 7px;"><span>2.3. В рамках Договора Исполнитель имеет право:</span></p>

<p><span>2.3.1. В соответствии с настоящим Договором Исполнитель вправе удерживать результат Работы в случае нарушения Заказчиком условий Договора и неисполнением (ненадлежащим исполнением) предусмотренных в нем обязательств.</span></p>

<p><span>2.3.2. Изменять сроки выполнения работ вследствие ненадлежащего выполнения Заказчиком обязательств по данному договору.</span></p>

<p style="margin-top: 7px;"><span>2.4. В соответствии с настоящим Договором Исполнитель обязан:</span></p>

<p><span>2.4.1. Выполнить работу надлежащим образом.</span></p>

<p><span>2.4.2. Предупредить Заказчика о любых обстоятельствах, способных повлиять на выполнение Работы, о неблагоприятных последствиях выполнения указаний Заказчика и обо всех иных обстоятельствах, которые могут повлиять на качество выполняемой Работы.</span></p>

<p><span>2.4.3. Гарантировать конфиденциальность полученной от Заказчика информации, в том числе пароли доступа в закрытые зоны сайта. Обеспечить возможность смены этих паролей администратором сайта. </span></p>

<p><span>2.5. Исполнитель за несанкционированное разглашение конфиденциальной информации несет ответственность в соответствии с действующим законодательством.</span></p>
<h2><span>3. Расчеты по Договору</span></h2>
<p><span>3.1. В соответствии с настоящим Договором стоимость выполненной Исполнителем Работы составляет 1000  рублей.</span></p>
<p><span>Заказчик обязуется внести оплату стоимости работ
        в течении 3-х рабочих дней с момента подписания данного договора. Оплата производиться любым удобным Заказчику способом: на расчетный счет исполнителя,
        наличными средствами или путем взаимозачета. </span></p>

<h2><span>4. Срок действия Договора</span></h2>
<p><span>4.1. Настоящий Договор вступает в законную силу с момента его подписания и действует до исполнения сторонами всех обязательств по данному договору.</span></p>

<h2><span>5. Ответственность сторон</span></h2>
<p><span>5.1. В случае неисполнения или ненадлежащего исполнения обязательств по настоящему Договору стороны несут ответственность в соответствии с нормами действующего законодательства Российской Федерации.</span></p>

<p><span>5.2. В случае наступления обстоятельств непреодолимой силы (форс-мажор), вызванных прямо или косвенно проявлениями, например,  пожара, наводнения, землетрясения, эпидемии, военных конфликтов и переворотов, административного вмешательства со стороны органов власти или правительственных ограничений и т.п., оказывающих влияние на выполнение сторонами обязательств по настоящему Договору, или иных обстоятельств вне контроля сторон выполнение этих обязательств откладывается до устранения указанных обстоятельств форс-мажора.</span></p>

<p><span>5.3. Сторона, ссылающаяся на форс-мажорные обстоятельства, обязана незамедлительно и в письменной форме известить другую сторону об их начале и окончании, а также представить для подтверждения указанных обстоятельств соответствующий акт компетентного органа.</span></p>

<h2><span>6. Порядок разрешения споров</span></h2>
<p><span>6.1. Споры и разногласия, возникающие в рамках настоящего Договора, разрешаются сторонами путем ведения переговоров.</span></p>

<p><span>6.2. В случае невозможности разрешить возникшую конфликтную ситуацию путем переговоров спор передается сторонами на рассмотрение в Арбитражный суд р. Бурятия.</span></p>

<h2><span>7. Заключительные положения</span></h2>
<p><span>7.1. Настоящий Договор и Приложения составлены в двух экземплярах, подписанных обеими сторонами. Оба экземпляра идентичны друг другу и имеют равную юридическую силу. У каждой стороны находится по одному экземпляру.</span></p>

<p><span>7.2. Любые изменения и дополнения к настоящему Договору должны быть составлены в письменной форме и подписаны обеими сторонами.</span></p>

<p><span>7.3. Вопросы, не урегулированные настоящим Договором, разрешаются в соответствии с действующим законодательством Российской Федерации.</span></p>

<h2><span>8. Реквизиты сторон</span></h2>
<table style="table-layout: auto;">
    <tr>
        <td>
            <p style="font-weight: bold;"><span>Исполнитель:</span></p>
        </td>
        <td>
        </td>
        <td>
            <p style="font-weight: bold;"><span>Заказчик:</span></p>
        </td>
    </tr>
    <tr style="position: relative;">
        <td>
            <p style="font-weight: bold;"><span>sdckjbw ekjcwjckn</span></p>
            <p><span>ИНН u2i3u49283</span></p>

                <p><span>ОГРНИП 9238409234982</span></p>

            <p><span>р/с 8349239482387492</span></p>
            <p><span>к/с 8372498723947829374982</span></p>
            <p><span>efiwbefibwfeiuwf</span></p>
            <p><span>БИК wkjbfkwjbfwf</span></p>
            <p><span>тел +7 (3012) 585-303</span></p>
        </td>
        <td>
        </td>
        <td style="vertical-align:top;">
            <p style="font-weight: bold;"><span>kjdbfkjwbfks</span></p>
            <p><span>ИНН 82491873987</span></p>

                <p><span> ОГРН 231231231</span></p>

        </td>
    </tr>
    <?php
        $company_signature_bottom = rand(85, 95);
        $client_signature_bottom = rand(80, 85);
        $company_print_bottom = rand(0, 15);
        $client_print_bottom = rand(0, 15);
        $company_signature_left = rand(15, 25);
        $client_signature_right = rand(170, 200);
        $company_print_left = rand(25, 35);
        $client_print_right = rand(75, 110);
        $company_transform = rand(-15, 15);
        $client_transform = rand(-15, 15);
    ?>
    <tr>
        <td>
            <p style="font-size: 8pt; margin-top: 10pt;"><span>директор</span></p>
{{--            <p><span>___________________/{{$contract->company->name_director_for_print}}</span></p>--}}
{{--            <img src="{{public_path('storage/' . $contract->company->signature)}}"--}}
{{--                 style="--}}
{{--                 width: 120px;--}}
{{--                 height: 80px;--}}
{{--                 position: absolute;--}}
{{--                 bottom: {{$company_signature_bottom}}px;--}}
{{--                 left: {{$company_signature_left}}px;">--}}
{{--            <img src="{{public_path('storage/' . $contract->company->print)}}"--}}
{{--                 style="--}}
{{--                 width: 150px;--}}
{{--                 height: 150px;--}}
{{--                 position: absolute;--}}
{{--                 bottom: {{$company_print_bottom}}px;--}}
{{--                 left: {{$company_print_left}}px;--}}
{{--                 transform: rotate({{$company_transform}}deg);">--}}
        </td>
        <td>
        </td>
        <td>
            <p style="font-size: 8pt; margin-top: 10pt;"><span>директор</span></p>
{{--            <p><span>__________________ /{{$contract->client->name_director_for_print}}</span></p>--}}
{{--            <img src="{{public_path('storage/' . $contract->client->signature)}}"--}}
{{--                 style="--}}
{{--                 width: 120px;--}}
{{--                 height: 80px;--}}
{{--                 position: absolute;--}}
{{--                 bottom: {{$client_signature_bottom}}px;--}}
{{--                 right: {{$client_signature_right}}px;">--}}
{{--            <img src="{{public_path('storage/' . $contract->client->print)}}"--}}
{{--                 style="--}}
{{--                 width: 150px;--}}
{{--                 height: 150px;--}}
{{--                 position: absolute;--}}
{{--                 bottom: {{$company_print_bottom}}px;--}}
{{--                 right: {{$client_print_right}}px;--}}
{{--                 transform: rotate({{$client_transform}}deg);">--}}
        </td>
    </tr>
</table>
<div class="page-break"></div>
<h1 style="text-align: center; margin-top: 0pt; margin-bottom: 0pt;"><span>АКТ № 12312312 от 2022 года</span><br />
    <span>приемки-передачи выполненных работ</span><br><br>
</h1>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;">
    <span >
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores harum incidunt sapiente. Ab aspernatur, at esse inventore molestias optio placeat porro possimus quod repellendus? Ab blanditiis ea error eum ex quidem, quis repellendus sunt ullam veritatis. Dolores earum exercitationem impedit porro sint. At, dolor facilis fugiat officiis quisquam repudiandae voluptas.
    </span>
</p>
<p><span>Исполнителем выполнены, а Заказчиком приняты следующие работы:</span></p><br>
<table class="ae" style="border: 1px solid black">
    <tr style="border: 1px solid black">
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>№</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>Наименование работ</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>Цена</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>Кол-во</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>Ед. изм</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>Без НДС</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>НДС</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>Сумма</span></p>
        </td>
    </tr>
    <tr style="border: 1px solid black">
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>1</span></p>
        </td>
        <td style="border: 1px solid black">
            <p><span></span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span></span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>1</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>шт</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span></span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>0</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span></span></p>
        </td>
    </tr>
    <tr style="border: 1px solid black">
        <td colspan="5" style="border: 1px solid black">
            <p style="text-align: right; margin-top: 0; margin-bottom: 0;"><span>Итого:</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span></span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span>0</span></p>
        </td>
        <td style="border: 1px solid black">
            <p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span></span></p>
        </td>
    </tr>
</table>
<p><span>Вышеперечисленные услуги выполнены полностью и в срок. Заказчик претензий по объему, качеству и срокам оказанных услуг не имеет. </span></p><br><br>
<table style="table-layout: auto;">
    <tr>
        <td>
            <p style="font-weight: bold"><span>Исполнитель:</span></p>
        </td>
        <td>
        </td>
        <td>
            <p style="font-weight: bold"><span>Заказчик:</span></p>
        </td>
    </tr>
    <tr>
        <td>
            <p style="font-weight: bold"><span></span></p>
        </td>
        <td>
        </td>
        <td>
            <p style="text-align: left; margin-top: 0; margin-bottom: 0; font-weight: bold;"><span></span></p>
        </td>
    </tr>
    <tr style=" position: relative;">
        <td>
            <p style="font-size: 8pt; margin-top: 10pt;"><span>директор</span></p>
{{--            <p><span>___________________/{{$contract->company->name_director_for_print}}</span></p>--}}
            <p><span>М.П.</span></p>
            <?php
                $signature_top = rand(-110, -120);
                $company_print_top = rand(-60, -40);
                $client_print_top = rand(-60, -40);
                $signature_left = rand(8, 12);
                $print_left = rand(-85, -55);
                $company_transform = rand(-15, 15);
                $client_transform = rand(-15, 15);
            ?>
{{--            <img src="{{public_path('storage/' . $contract->company->signature)}}"--}}
{{--                 style="--}}
{{--                 width: 120px;--}}
{{--                 height: 80px;--}}
{{--                 position: relative;--}}
{{--                 top: {{$signature_top}}px;--}}
{{--                 left: {{$signature_left}}px;--}}
{{--                 ">--}}
{{--            <img src="{{public_path('storage/' . $contract->company->print)}}"--}}
{{--                 style="--}}
{{--                 width: 150px;--}}
{{--                 height: 150px;--}}
{{--                 position: relative;--}}
{{--                 top: {{$company_print_top}}px;--}}
{{--                 left: {{$print_left}}px;--}}
{{--                 transform: rotate(-{{$company_transform}}deg);">--}}
        </td>
        <td>
        </td>
        <td>
            <p style="font-size: 8pt; margin-top: 10pt;"><span>директор</span></p>
{{--            <p><span>__________________ /{{$contract->client->name_director_for_print}}</span></p>--}}
            <p><span>М.П.</span></p>
{{--            <img src="{{public_path('storage/' . $contract->client->signature)}}"--}}
{{--                 style="--}}
{{--                 width: 120px;--}}
{{--                 height: 80px;--}}
{{--                 position: relative;--}}
{{--                 top: {{$signature_top}}px;--}}
{{--                 left: {{$signature_left}}px;">--}}
{{--            <img src="{{public_path('storage/' . $contract->client->print)}}"--}}
{{--                 style="--}}
{{--                 width: 150px;--}}
{{--                 height: 150px;--}}
{{--                 position: relative;--}}
{{--                 top: {{$client_print_top}}px;--}}
{{--                 left: {{$print_left}}px;--}}
{{--                 transform: rotate({{$client_transform}}deg);">--}}
        </td>
    </tr>
</table>
</body>
</html>

